:- module(symac_distro_render,
    [ render_ir/2
    ]).

:- use_module(library(lists)).

render_ir(distro_ir(Host, nix, Packages, Services, Environment,
                    Features, Roles, Secrets), Text) :-
    !,
    phrase(nix_module(Host, Packages, Services, Environment,
                      Features, Roles, Secrets), Codes),
    string_codes(Text, Codes).
render_ir(distro_ir(Host, guix, Packages, Services, Environment,
                    Features, Roles, Secrets), Text) :-
    !,
    phrase(guix_module(Host, Packages, Services, Environment,
                       Features, Roles, Secrets), Codes),
    string_codes(Text, Codes).
render_ir(distro_ir(_, Backend, _, _, _, _, _, _), _) :-
    throw(error(domain_error(symac_distro_backend, Backend), _)).

nix_module(Host, Packages, Services, Environment, Features, Roles, Secrets) -->
    "{ pkgs, ... }:
",
    "{
",
    "  # Generated by Symac's deterministic Prolog distro compiler.
",
    "  # host: ", text_atom(Host), "
",
    "  environment.systemPackages = map (name: builtins.getAttr name pkgs) [
",
    nix_package_lines(Packages),
    "  ];
",
    nix_services(Services),
    nix_environment(Environment),
    metadata_comments("feature", Features),
    metadata_comments("role", Roles),
    secret_comments(Secrets),
    "}
".

nix_package_lines([]) --> [].
nix_package_lines([package(_, Name)|Rest]) -->
    "    ", quoted(Name), "
",
    nix_package_lines(Rest).

nix_services([]) --> [].
nix_services([Service-State|Rest]) -->
    nix_service(Service, State),
    nix_services(Rest).

nix_service(openssh, enabled) --> "  services.openssh.enable = true;
".
nix_service(openssh, disabled) --> "  services.openssh.enable = false;
".
nix_service(Service, _) -->
    { throw(error(existence_error(nix_service_mapping, Service), _)) }.

nix_environment([]) --> [].
nix_environment(Environment) -->
    "  environment.sessionVariables = {
",
    nix_environment_lines(Environment),
    "  };
".

nix_environment_lines([]) --> [].
nix_environment_lines([Key-Value|Rest]) -->
    "    ", quoted(Key), " = ", quoted(Value), ";
",
    nix_environment_lines(Rest).

guix_module(Host, Packages, Services, Environment, Features, Roles, Secrets) -->
    ";; Generated by Symac's deterministic Prolog distro compiler.
",
    ";; host: ", text_atom(Host), "
",
    "(use-modules (gnu packages) (gnu services) (gnu services ssh))

",
    "(define %symac-packages
",
    "  (map specification->package
",
    "       '(",
    guix_package_names(Packages),
    ")))

",
    "(define %symac-system-services
",
    "  (list",
    guix_services(Services),
    "))

",
    "(define %symac-environment
",
    "  '(",
    guix_environment(Environment),
    "))
",
    scheme_metadata_comments("feature", Features),
    scheme_metadata_comments("role", Roles),
    scheme_secret_comments(Secrets).

guix_package_names([]) --> [].
guix_package_names([package(_, Name)]) -->
    quoted(Name).
guix_package_names([package(_, Name)|Rest]) -->
    quoted(Name), " ",
    guix_package_names(Rest).

guix_services([]) --> [].
guix_services([Service-State|Rest]) -->
    guix_service(Service, State),
    guix_services(Rest).

guix_service(openssh, enabled) --> "
    (service openssh-service-type)".
guix_service(openssh, disabled) --> [].
guix_service(Service, _) -->
    { throw(error(existence_error(guix_service_mapping, Service), _)) }.

guix_environment([]) --> [].
guix_environment([Key-Value]) -->
    "(", quoted(Key), " . ", quoted(Value), ")".
guix_environment([Key-Value|Rest]) -->
    "(", quoted(Key), " . ", quoted(Value), ") ",
    guix_environment(Rest).

metadata_comments(_, []) --> [].
metadata_comments(Label, [Item|Rest]) -->
    "  # ", text_atom(Label), ": ", term_text(Item), "
",
    metadata_comments(Label, Rest).

secret_comments([]) --> [].
secret_comments([Name-Source|Rest]) -->
    "  # secret source only; no secret value stored: ",
    text_value(Name), " <- ", term_text(Source), "
",
    secret_comments(Rest).

scheme_metadata_comments(_, []) --> [].
scheme_metadata_comments(Label, [Item|Rest]) -->
    ";; ", text_atom(Label), ": ", term_text(Item), "
",
    scheme_metadata_comments(Label, Rest).

scheme_secret_comments([]) --> [].
scheme_secret_comments([Name-Source|Rest]) -->
    ";; secret source only; no secret value stored: ",
    text_value(Name), " <- ", term_text(Source), "
",
    scheme_secret_comments(Rest).

quoted(Value) -->
    { value_string(Value, String),
      escape_string(String, Escaped),
      string_codes(Escaped, Codes)
    },
    """, Codes, """.

text_atom(Atom) -->
    { atom_string(Atom, String), string_codes(String, Codes) },
    Codes.

text_value(Value) -->
    { value_string(Value, String), string_codes(String, Codes) },
    Codes.

term_text(Term) -->
    { with_output_to(string(String), write_term(Term, [quoted(true)])),
      string_codes(String, Codes)
    },
    Codes.

value_string(Value, String) :-
    ( string(Value) ->
        String = Value
    ; atom(Value) ->
        atom_string(Value, String)
    ; number_string(Value, String)
    ).

escape_string(Input, Output) :-
    string_codes(Input, Codes),
    phrase(escaped_codes(Codes), Escaped),
    string_codes(Output, Escaped).

escaped_codes([]) --> [].
escaped_codes([0'\|Rest]) --> "\\", escaped_codes(Rest).
escaped_codes([0'"|Rest]) --> "\"", escaped_codes(Rest).
escaped_codes([0'\n|Rest]) --> "\n", escaped_codes(Rest).
escaped_codes([Code|Rest]) --> [Code], escaped_codes(Rest).
