(defpackage #:symac.task
  (:use #:cl)
  (:export
   #:invalid-task-state
   #:invalid-slice-state
   #:missing-verification-evidence
   #:slice-dependency-cycle
   #:make-task
   #:task-id
   #:task-title
   #:task-state
   #:task-tags
   #:task-priority
   #:task-scheduled
   #:task-deadline
   #:task-dependencies
   #:task-metadata
   #:schedule-task
   #:set-task-deadline
   #:transition-task
   #:make-slice
   #:slice-id
   #:slice-task-id
   #:slice-title
   #:slice-state
   #:slice-dependencies
   #:slice-verification-required
   #:slice-verification-evidence
   #:slice-agent-session-id
   #:record-slice-verification
   #:verify-slice
   #:assign-slice-session
   #:make-task-store
   #:store-task
   #:store-slice
   #:find-task
   #:find-slice
   #:add-slice-dependency))
